# This is a basic workflow to help deploy CloudFormation stacks with Actions

name: Deploy

on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "deploy"
  deploy:
    name: Deploy VPC
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Environment variable available for this job
    env:
      region: eu-west-1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.region }}

    - name: Deploy to Foobar VPC with CloudFormation
      id: vpc-stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: foobar-vpc
        template: stacks/foo-vpc.yaml
        no-fail-on-empty-changeset: "1"
